export const NAV_LEVEL2 = [
  {
    id: 0,
    menuId: "APPLICATION",
    menuValue: "직영몰",
    order: 1,
    active: true,
  },
  {
    id: 1,
    menuId: "BRAND",
    menuValue: "브랜드",
    order: 2,
    active: true,
  },
];

export const NAV_LEVEL3 = {
  APPLICATION: [
    {
      id: 0,
      menuId: "APM",
      menuValue: "APM",
      order: 1,
      active: true,
    },
    {
      id: 1,
      menuId: "ATM",
      menuValue: "ATM",
      order: 2,
      active: true,
    },
    {
      id: 2,
      menuId: "BP",
      menuValue: "BP",
      order: 3,
      active: true,
    },
    {
      id: 3,
      menuId: "Etd",
      menuValue: "ETD",
      order: 4,
      active: true,
    },
    {
      id: 4,
      menuId: "Inn",
      menuValue: "INN",
      order: 5,
      active: true,
    },
    {
      id: 5,
      menuId: "Oll",
      menuValue: "OLL",
      order: 6,
      active: true,
    },
    {
      id: 6,
      menuId: "Ast",
      menuValue: "AST",
      order: 7,
      active: true,
    },
    {
      id: 7,
      menuId: "BA",
      menuValue: "BA",
      order: 8,
      active: true,
    },
    {
      id: 8,
      menuId: "Cub",
      menuValue: "CUB",
      order: 9,
      active: true,
    },
    {
      id: 9,
      menuId: "CT",
      menuValue: "CT",
      order: 10,
      active: true,
    },
    {
      id: 10,
      menuId: "Epr",
      menuValue: "EPR",
      order: 11,
      active: true,
    },
  ],
  BRAND: [
    {
      id: 0,
      menuId: "Amorepacific",
      menuValue: "AMOREPACIFIC",
      order: 1,
      active: true,
    },
    {
      id: 1,
      menuId: "Hanyul",
      menuValue: "HANYUL",
      order: 2,
      active: true,
    },
    {
      id: 2,
      menuId: "Happybath",
      menuValue: "HAPPYBATH",
      order: 3,
      active: true,
    },
    {
      id: 3,
      menuId: "Hera",
      menuValue: "HERA",
      order: 4,
      active: true,
    },
    {
      id: 4,
      menuId: "Iope",
      menuValue: "IOPE",
      order: 5,
      active: true,
    },
    {
      id: 5,
      menuId: "Laneige",
      menuValue: "LANEIGE",
      order: 6,
      active: true,
    },
    {
      id: 6,
      menuId: "Lirikos",
      menuValue: "LIRIKOS",
      order: 7,
      active: true,
    },
    {
      id: 7,
      menuId: "Lirikosmarine",
      menuValue: "LIRIKOSMARINE",
      order: 8,
      active: true,
    },
    {
      id: 8,
      menuId: "Mamonde",
      menuValue: "MAMONDE",
      order: 9,
      active: true,
    },
    {
      id: 9,
      menuId: "Miseenscene",
      menuValue: "MISEENSCENE",
      order: 10,
      active: true,
    },
    {
      id: 10,
      menuId: "Primera",
      menuValue: "PRIMERA",
      order: 11,
      active: true,
    },
    {
      id: 11,
      menuId: "Ryo",
      menuValue: "RYO",
      order: 12,
      active: true,
    },
    {
      id: 12,
      menuId: "Steady",
      menuValue: "STEADY",
      order: 13,
      active: true,
    },
    {
      id: 13,
      menuId: "Sulwhasoo",
      menuValue: "SULWHASOO",
      order: 14,
      active: true,
    },
    {
      id: 14,
      menuId: "Vitalbeautie",
      menuValue: "VITALBEAUTIE",
      order: 15,
      active: true,
    },
  ],
  RESPONSE_MALL: [
    {
      id: 0,
      menuId: "ALL",
      menuValue: "ALL",
      order: 1,
      active: true,
    },
    {
      id: 1,
      menuId: "Lng",
      menuValue: "LNG",
      order: 2,
      active: true,
    },
    {
      id: 2,
      menuId: "BA",
      menuValue: "BA",
      order: 3,
      active: true,
    },
    {
      id: 3,
      menuId: "BP",
      menuValue: "BP",
      order: 4,
      active: true,
    },
    {
      id: 4,
      menuId: "Swh",
      menuValue: "SWH",
      order: 5,
      active: true,
    },
    {
      id: 5,
      menuId: "ATM",
      menuValue: "ATM",
      order: 6,
      active: true,
    },
    {
      id: 6,
      menuId: "APM",
      menuValue: "APM",
      order: 7,
      active: true,
    },
    {
      id: 7,
      menuId: "Etd",
      menuValue: "ETD",
      order: 8,
      active: true,
    },
    {
      id: 8,
      menuId: "Epr",
      menuValue: "EPR",
      order: 9,
      active: true,
    },
    {
      id: 9,
      menuId: "Ast",
      menuValue: "AST",
      order: 10,
      active: true,
    },
    {
      id: 10,
      menuId: "Oll",
      menuValue: "OLL",
      order: 11,
      active: true,
    },
    {
      id: 11,
      menuId: "Inn",
      menuValue: "INN",
      order: 12,
      active: true,
    },
    {
      id: 12,
      menuId: "CS",
      menuValue: "CS",
      order: 13,
      active: true,
    },
    {
      id: 13,
      menuId: "CT",
      menuValue: "CT",
      order: 14,
      active: true,
    },
    {
      id: 14,
      menuId: "CP",
      menuValue: "CP",
      order: 15,
      active: true,
    },
    {
      id: 15,
      menuId: "Cub",
      menuValue: "CUB",
      order: 16,
      active: true,
    },
    {
      id: 16,
      menuId: "HH",
      menuValue: "HH",
      order: 17,
      active: true,
    },
  ],
};
