export const treemenu = {
  직영몰: [
    {
      id: 0,
      menuId: "APMall",
      menuValue: "APMall",
      order: 1,
      active: true,
    },
    {
      id: 1,
      menuId: "Aritaum",
      menuValue: "Aritaum",
      order: 2,
      active: true,
    },
    {
      id: 2,
      menuId: "BeautyPoint",
      menuValue: "BeautyPoint",
      order: 3,
      active: true,
    },
    {
      id: 3,
      menuId: "Etude",
      menuValue: "Etude",
      order: 4,
      active: true,
    },
    {
      id: 4,
      menuId: "Innisfree",
      menuValue: "Innisfree",
      order: 5,
      active: true,
    },
    {
      id: 5,
      menuId: "Osulloc",
      menuValue: "Osulloc",
      order: 6,
      active: true,
    },
    {
      id: 6,
      menuId: "Aestura",
      menuValue: "Aestura",
      order: 7,
      active: true,
    },
    {
      id: 7,
      menuId: "BeautyAngel",
      menuValue: "BeautyAngel",
      order: 8,
      active: true,
    },
    {
      id: 8,
      menuId: "cubeme",
      menuValue: "cubeme",
      order: 9,
      active: true,
    },
    {
      id: 9,
      menuId: "COLORTAILOR",
      menuValue: "COLORTAILOR",
      order: 10,
      active: true,
    },
  ],
  브랜드: [
    {
      id: 0,
      menuId: "AMOREPACIFIC",
      menuValue: "AMOREPACIFIC",
      order: 1,
      active: true,
    },
    {
      id: 1,
      menuId: "HANYUL",
      menuValue: "HANYUL",
      order: 2,
      active: true,
    },
    {
      id: 2,
      menuId: "HAPPYBATH",
      menuValue: "HAPPYBATH",
      order: 3,
      active: true,
    },
    {
      id: 3,
      menuId: "HERA",
      menuValue: "HERA",
      order: 4,
      active: true,
    },
    {
      id: 4,
      menuId: "IOPE",
      menuValue: "IOPE",
      order: 5,
      active: true,
    },
    {
      id: 5,
      menuId: "LANEIGE",
      menuValue: "LANEIGE",
      order: 6,
      active: true,
    },
    {
      id: 6,
      menuId: "LIRIKOS",
      menuValue: "LIRIKOS",
      order: 7,
      active: true,
    },
    {
      id: 7,
      menuId: "LIRIKOSMARINE",
      menuValue: "LIRIKOSMARINE",
      order: 8,
      active: true,
    },
    {
      id: 8,
      menuId: "MAMONDE",
      menuValue: "MAMONDE",
      order: 9,
      active: true,
    },
    {
      id: 9,
      menuId: "MISEENSCENE",
      menuValue: "MISEENSCENE",
      order: 10,
      active: true,
    },
    {
      id: 10,
      menuId: "PRIMERA",
      menuValue: "PRIMERA",
      order: 11,
      active: true,
    },
    {
      id: 11,
      menuId: "RYO",
      menuValue: "RYO",
      order: 12,
      active: true,
    },
    {
      id: 12,
      menuId: "STEADY",
      menuValue: "STEADY",
      order: 13,
      active: true,
    },
    {
      id: 13,
      menuId: "SULWHASOO",
      menuValue: "SULWHASOO",
      order: 14,
      active: true,
    },
    {
      id: 14,
      menuId: "VITALBEAUTIE",
      menuValue: "VITALBEAUTIE",
      order: 15,
      active: true,
    },
  ],
};

export const devices = [
  {
    id: 0,
    menuId: "Galaxy S8+",
    menuValue: "Galaxy S8+",
    order: 1,
    active: true,
  },
  {
    id: 1,
    menuId: "Galaxy S105G",
    menuValue: "Galaxy S105G",
    order: 2,
    active: true,
  },
  {
    id: 2,
    menuId: "Galaxy A8",
    menuValue: "Galaxy A8",
    order: 3,
    active: true,
  },
  {
    id: 3,
    menuId: "Galaxy Note9",
    menuValue: "Galaxy Note9",
    order: 4,
    active: true,
  },
  {
    id: 4,
    menuId: "Galaxy Note10",
    menuValue: "Galaxy Note10",
    order: 5,
    active: true,
  },
];

export const countries = [
  {
    id: 0,
    menuId: "한국",
    menuValue: "한국",
    order: 1,
    active: true,
  },
  {
    id: 1,
    menuId: "홍콩영문",
    menuValue: "홍콩영문",
    order: 2,
    active: true,
  },
  {
    id: 2,
    menuId: "홍콩중문",
    menuValue: "홍콩중문",
    order: 3,
    active: true,
  },
  {
    id: 3,
    menuId: "국제영문",
    menuValue: "국제영문",
    order: 4,
    active: true,
  },
  {
    id: 4,
    menuId: "싱가포르 영문",
    menuValue: "싱가포르 영문",
    order: 5,
    active: true,
  },
  {
    id: 5,
    menuId: "중국",
    menuValue: "중국",
    order: 6,
    active: true,
  },
  {
    id: 6,
    menuId: "말레이시아 영문",
    menuValue: "말레이시아 영문",
    order: 7,
    active: true,
  },
  {
    id: 7,
    menuId: "베트남",
    menuValue: "베트남",
    order: 8,
    active: true,
  },
  {
    id: 8,
    menuId: "인도네시아",
    menuValue: "인도네시아",
    order: 9,
    active: true,
  },
  {
    id: 9,
    menuId: "캐나다 영문",
    menuValue: "캐나다 영문",
    order: 10,
    active: true,
  },
  {
    id: 10,
    menuId: "태국",
    menuValue: "태국",
    order: 11,
    active: true,
  },
  {
    id: 11,
    menuId: "대만 중문",
    menuValue: "대만 중문",
    order: 12,
    active: true,
  },
];
